### ISSUE TITLE
Trabajar con funciones sincronías también es una opción 

### ISSUE THREAD

**Issue by betsyvies** [Eunice17/LIM014-mdlinks#2]
Eunice, veo que estas trabajando con métodos asíncronos de node, también puedes hacerlo se forma sincrona, no todo tiene que ser asíncrono, por ejemplo el método `.readFile` tiene su contraparte sincrona [.readFileSync](https://www.geeksforgeeks.org/node-js-fs-readfilesync-method/). Cuéntame si es porque quieres trabajarlo todo de forma asincrona.

**Comment by Eunice17** [comment]
Gracias por la sugerencia. Yo lo quiero trabajar con promesas, para entender mejor como funciona las funciones asíncronas y promesas. ¿Es una buena práctica lo que estoy haciendo?
Creo que utilizaré las funciones (asíncronas) definidas por `Node` para mi función que retorna un arreglo con los links validados, entonces tendría una función que trabaja con Promesas definidas por mi y otra función haciendo uso de las funciones asíncronas definidas por `Node`.
